[contact_plan]
name = "contact_plan_storage"
max_time_in_sec = 300
cpus   = "1.0"   
memory = "1g"

[contact_plan.defaults]
rate_in_bits_per_sec = 300000000
range = 1

# Node Definitions
[[nodes]]
id = 1
isDtnNode = false

[[nodes]]
id = 2
isDtnNode = true

[[nodes]]
id = 3
isDtnNode = true

[[edges]]
from         = 1
to           = 2
start_in_sec = 0
end_in_sec   = 300
bidirected   = true

[[edges]]
from         = 2
to           = 3
start_in_sec = 90
end_in_sec   = 300
bidirected   = true
