services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: "network_1.env"
    environment:
      APP_NAME: "test donkey"
      PS1: "test_dtn# "
      NODE: 2
      HOST_TUN_IPV6_ADDR:  "fd00:ffff:2::1"
      HOST_LWIP_IPV6_ADDR: "fd00:ffff:2::2"
      INT_1: "enp0s8, fd00:1:2::2, fd00:1:2::1"
      NEIGH_1: "enp0s8, fd00:1:2::1, 02:00:01:00:02:01"

      INT_2: "enp0s9, fd00:2:3::2, fd00:2:3::3, fd00:3:4::4"
      NEIGH_2: "enp0s9, fd00:2:3::3, 02:00:02:00:03:03"
    container_name: test
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    # entrypoint: ["/root/init_dtn_node.sh"]
    volumes:
      - .:/root                  # mirrors your entire py_cgr/ directory live
    working_dir: /root
    stdin_open: true            # keeps stdin open for interactive shell
    tty: true                   # allocates a pseudo-TTY (so bash looks normal)
    # Uncomment if you need IPv6 support at the network level:
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=0
 