services:

  dtn_node_0:
    environment:
      APP_NAME: "plain eagle"
      DEBUG: true
      PS1: "reg_node_0# "
      NODE: 0
      INT_1: "enp0s9, fd00:0:1::1, fd00:0:1::2, fd00:ffff::, fd00:1:2::, fd00:2:3::"

      NEIGH_1: "enp0s9, fd00:0:1::2, 02:00:00:00:01:01"
    build:
      context: .
      dockerfile: Dockerfile.reg
    container_name: reg_node_0
    privileged: true
    entrypoint: ["/root/init_reg_node.sh"]
    networks:
      net_01:
        mac_address: "02:00:00:00:01:00"
    cap_add:
      - NET_ADMIN

  dtn_node_1:
    environment:
      IS_DOCKER: true
      APP_NAME: "fast monkey"
      DEBUG: true
      PS1: "dtn_node_1# "
      NODE: 1
      HOST_TUN_IPV6_ADDR:  "fd00:ffff:1::1"
      HOST_LWIP_IPV6_ADDR: "fd00:ffff:1::2"
      INT_1: "enp0s8, fd00:0:1::2, fd00:0:1::1"
      NEIGH_1: "enp0s8, fd00:0:1::1, 02:00:00:00:01:00"
      # ip -6 addr add fd00:12::1/64 dev enp0s9 || true
      # ip -6 route add fd00:22::/64 via fd00:12::2 dev enp0s9 || true
      # ip -6 route add fd00:23::/64 via fd00:12::2 dev enp0s9 || true
      # ip -6 route add fd00:33::/64 via fd00:12::2 dev enp0s9 || true
      # interface, addr, via, routes...
      INT_2: "enp0s9, fd00:1:2::1, fd00:1:2::2, fd00:ffff::, fd00:2:3::"
      NEIGH_2: "enp0s9, fd00:1:2::2, 02:00:01:00:02:02"
    build:
      context: .
      dockerfile: Dockerfile.dtn
      # dockerfile: Dockerfile.reg
    container_name: dtn_node_1
    privileged: true
    entrypoint: ["/root/init_dtn_node.sh"]
    # entrypoint: ["/root/init_reg_node.sh"]
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net_01:
        mac_address: "02:00:00:00:01:01"
      net_12:
        mac_address: "02:00:01:00:02:01"
    cap_add:
      - NET_ADMIN
    depends_on:
      - dtn_node_0
    
  dtn_node_2:
    environment:
      APP_NAME: "orange rabbit"
      DEBUG: true
      PS1: "dtn_node_2# "
      NODE: 2
      HOST_TUN_IPV6_ADDR:  "fd00:ffff:2::1"
      HOST_LWIP_IPV6_ADDR: "fd00:ffff:2::2"
      INT_1: "enp0s8, fd00:1:2::2, fd00:1:2::1, fd00:ffff::, fd00:0:1::"
      INT_2: "enp0s9, fd00:2:3::1, fd00:2:3::2, fd00:ffff::"
      # INT_2: "enp0s9, fd00:2:3::1, fd00:2:3::2, fd00:ffff::, fd00:3:4::"

      NEIGH_1: "enp0s8, fd00:1:2::1, 02:00:01:00:02:01"
      NEIGH_2: "enp0s9, fd00:2:3::2, 02:00:02:00:03:03"
    build:
      context: .
      dockerfile: Dockerfile.dtn
      # dockerfile: Dockerfile.reg
    container_name: dtn_node_2
    privileged: true
    entrypoint: ["/root/init_dtn_node.sh"]
    # entrypoint: ["/root/init_reg_node.sh"]
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net_12:
        mac_address: "02:00:01:00:02:02"
      net_23:
        mac_address: "02:00:02:00:03:02"
    cap_add:
      - NET_ADMIN
    depends_on:
      - dtn_node_1

  dtn_node_3:
    environment:
      APP_NAME: "blue sloth"
      DEBUG: true
      PS1: "dtn_node_3# "
      NODE: 3
      HOST_TUN_IPV6_ADDR:  "fd00:ffff:3::1"
      HOST_LWIP_IPV6_ADDR: "fd00:ffff:3::2"
      INT_1: "enp0s8, fd00:2:3::2, fd00:2:3::1, fd00:ffff::, fd00:1:2::, fd00:0:1::"

      NEIGH_1: "enp0s8, fd00:2:3::1, 02:00:02:00:03:02"
    build:
      context: .
      dockerfile: Dockerfile.dtn
      # dockerfile: Dockerfile.reg
    container_name: dtn_node_3
    privileged: true
    entrypoint: ["/root/init_dtn_node.sh"]
    # entrypoint: ["/root/init_reg_node.sh"]
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net_23:
        mac_address: "02:00:02:00:03:03"
      # net_34:
      #   mac_address: "02:00:03:00:04:03"
    cap_add:
      - NET_ADMIN
    depends_on:
      - dtn_node_2

  traffic_node_3:
    image: nicolaka/netshoot
    container_name: traffic_node_3
    network_mode: "service:dtn_node_3"   # shares exact same network namespace as node_1
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - dtn_node_3

  traffic_monitor:
    image: nicolaka/netshoot
    container_name: traffic_monitor
    network_mode: host                        # sees all Docker bridge interfaces
    command: sleep infinity  # -U = unbuffered, stdout stream
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - dtn_node_0
      - dtn_node_1
      - dtn_node_2
      - dtn_node_3
    volumes:
      - ./captures:/captures
    logging:
      driver: "none"

networks:
  net_01:
    enable_ipv6: true
    internal: true
  net_12:
    enable_ipv6: true
    internal: true
  net_23:
    enable_ipv6: true
    internal: true
  # net_34:
  #   enable_ipv6: true
  #   internal: true