FROM debian:bookworm-slim
 
RUN apt-get update && apt-get install -y \
    iproute2 \
    iptables \
    procps \
    iputils-ping \
    tcpdump \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*
 
WORKDIR /root/
 
COPY init_reg_node.sh .
COPY init_routes.sh .
RUN chmod +x init_reg_node.sh init_routes.sh
 