# Step 1: Use a lightweight build image
FROM debian:bookworm-slim AS builder

# Step 2: Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpcap-dev \
    && rm -rf /var/lib/apt/lists/*

# Step 3: Set the working directory
WORKDIR /app

COPY . .

RUN make

# docker build -f Dockerfile.build  -t dtn_node_build .