[contact_plan]
name = "contact_plan_ping_cgr"
max_time_in_sec = 1000

[contact_plan.defaults]
rate_in_bits_per_sec = 200
range = 1

# Node Definitions
[[nodes]]
id = 1
isDtnNode = false

[[nodes]]
id = 2
isDtnNode = true

[[nodes]]
id = 3
isDtnNode = true

[[nodes]]
id = 4
isDtnNode = true

[[nodes]]
id = 5
isDtnNode = true

# Edge Definitions
[[edges]]
from = 1
to = 2
start_in_sec = 0
end_in_sec = 1000
bidirected = true

[[edges]]
from = 2
to = 3
start_in_sec = 0
end_in_sec = 20
bidirected = true

[[edges]]
from = 3
to = 4
start_in_sec = 0
end_in_sec = 1000
bidirected = true

[[edges]]
from = 2
to = 5
start_in_sec = 20
end_in_sec = 1000
bidirected = true

[[edges]]
from = 4
to = 5
start_in_sec = 0
end_in_sec = 1000
bidirected = true