[contact_plan]
name = "contact_plan_throughput"
max_time_in_sec = 300

[contact_plan.defaults]
rate_in_bits_per_sec  = 128
range = 1

# Node Definitions
[[nodes]]
id = 1
isDtnNode = false

[[nodes]]
id = 2
isDtnNode = true

[[nodes]]
id = 3
isDtnNode = true

[[nodes]]
id = 10
isDtnNode = false

[[edges]]
from         = 1
to           = 2
start_in_sec = 0
end_in_sec   = 300
bidirected   = true

[[edges]]
from         = 2
to           = 3
start_in_sec = 0
end_in_sec   = 300
bidirected   = true

[[edges]]
from         = 3
to           = 10
start_in_sec = 0
end_in_sec   = 300
bidirected   = true
