FROM debian:bookworm-slim AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libpcap-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /repo
COPY . .
RUN make -C tests clean && make -C tests
# RUN make -C tests

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    libpcap0.8 \
    python3 \
    libpython3.11 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /repo/tests/lwip_tun_test /usr/local/bin/lwip_tun_test

ENTRYPOINT ["lwip_tun_test"]
