services:
  node1:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node1
    privileged: true
    hostname: node1
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_udp_storage/node1.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_udp_storage/node1.toml
    networks:
      net-node1-node2:
        mac_address: 00:01:00:02:00:01
    deploy:
      resources:
        limits:
          cpus: '1.0'
  node2:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node2
    privileged: true
    hostname: node2
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_udp_storage/node2.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_udp_storage/node2.toml
    networks:
      net-node1-node2:
        mac_address: 00:01:00:02:00:02
      net-node2-node3:
        mac_address: 00:02:00:03:00:02
    deploy:
      resources:
        limits:
          cpus: '1.0'
  node3:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node3
    privileged: true
    hostname: node3
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_udp_storage/node3.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_udp_storage/node3.toml
    networks:
      net-node2-node3:
        mac_address: 00:02:00:03:00:03
    deploy:
      resources:
        limits:
          cpus: '1.0'
  capture:
    image: nicolaka/netshoot
    container_name: capture
    network_mode: host
    entrypoint:
    - sh
    - /repo/networks/capture.sh
    privileged: true
    environment:
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
      PLAN_NAME: contact_plan_udp_storage
    volumes:
    - ../..:/repo
networks:
  net-node1-node2:
    driver: bridge
    enable_ipv6: true
  net-node2-node3:
    driver: bridge
    enable_ipv6: true
