[contact_plan]
name = "contact_plan_throughput"
max_time_in_sec = 100
cpus   = "1.0"   
memory = "1g"

[contact_plan.defaults]
rate_in_bits_per_sec  = 1028
range = 1

# Node Definitions
[[nodes]]
id = 1
isDtnNode = false

[[nodes]]
id = 2
isDtnNode = true

[[nodes]]
id = 3
isDtnNode = true

[[nodes]]
id = 4
isDtnNode = true

[[nodes]]
id = 5
isDtnNode = true

[[nodes]]
id = 6
isDtnNode = true

[[edges]]
from         = 1
to           = 2
start_in_sec = 0
end_in_sec   = 1000
bidirected   = true

[[edges]]
from         = 2
to           = 3
start_in_sec = 10
end_in_sec   = 20
bidirected   = true

[[edges]]
from         = 2
to           = 4
start_in_sec = 0
end_in_sec   = 100
bidirected   = true

[[edges]]
from         = 3
to           = 6
start_in_sec = 15
end_in_sec   = 100
bidirected   = true

[[edges]]
from         = 4
to           = 5
start_in_sec = 25
end_in_sec   = 100
bidirected   = true

[[edges]]
from         = 5
to           = 6
start_in_sec = 30
end_in_sec   = 100
bidirected   = true


