services:
  node1:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node1
    privileged: true
    hostname: node1
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node1.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node1.toml
    networks:
      net-node1-node2:
        mac_address: 00:01:00:02:00:01
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  node2:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node2
    privileged: true
    hostname: node2
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node2.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node2.toml
    networks:
      net-node1-node2:
        mac_address: 00:01:00:02:00:02
      net-node2-node3:
        mac_address: 00:02:00:03:00:02
      net-node2-node4:
        mac_address: 00:02:00:04:00:02
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  node3:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node3
    privileged: true
    hostname: node3
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node3.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node3.toml
    networks:
      net-node2-node3:
        mac_address: 00:02:00:03:00:03
      net-node3-node6:
        mac_address: 00:03:00:06:00:03
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  node4:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node4
    privileged: true
    hostname: node4
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node4.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node4.toml
    networks:
      net-node2-node4:
        mac_address: 00:02:00:04:00:04
      net-node4-node5:
        mac_address: 00:04:00:05:00:04
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  node5:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node5
    privileged: true
    hostname: node5
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node5.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node5.toml
    networks:
      net-node4-node5:
        mac_address: 00:04:00:05:00:05
      net-node5-node6:
        mac_address: 00:05:00:06:00:05
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  node6:
    build:
      context: ../..
      dockerfile: Dockerfile.node
    container_name: node6
    privileged: true
    hostname: node6
    environment:
      DTN_CONFIG_PATH: /repo/networks/contact_plan_throughput/node6.toml
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
    volumes:
    - ../..:/repo
    working_dir: /repo
    cap_add:
    - NET_ADMIN
    entrypoint:
    - python3
    - /repo/init_node.py
    - /repo/networks/contact_plan_throughput/node6.toml
    networks:
      net-node3-node6:
        mac_address: 00:03:00:06:00:06
      net-node5-node6:
        mac_address: 00:05:00:06:00:06
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  capture:
    image: nicolaka/netshoot
    container_name: capture
    network_mode: host
    entrypoint:
    - sh
    - /repo/networks/capture.sh
    privileged: true
    environment:
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
      PLAN_NAME: contact_plan_throughput
    volumes:
    - ../..:/repo
  metrics:
    build:
      context: ../..
      dockerfile: Dockerfile.metrics
    container_name: metrics
    environment:
      PLAN_NAME: contact_plan_throughput
      TEST_CASE_NUMBER: ${TEST_CASE_NUMBER}
      METRICS_OUT: /repo/networks/contact_plan_throughput/captures/${TEST_CASE_NUMBER}/metrics.jsonl
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ../..:/repo
    command:
    - python3
    - /repo/networks/get_metrics.py
networks:
  net-node1-node2:
    driver: bridge
    enable_ipv6: true
  net-node2-node3:
    driver: bridge
    enable_ipv6: true
  net-node2-node4:
    driver: bridge
    enable_ipv6: true
  net-node3-node6:
    driver: bridge
    enable_ipv6: true
  net-node4-node5:
    driver: bridge
    enable_ipv6: true
  net-node5-node6:
    driver: bridge
    enable_ipv6: true
