[contact_plan]
name                 = "contact_plan_sateliot"
max_time_in_sec      = 90000

[contact_plan.defaults]
rate_in_bits_per_sec = 300000000
range                = 1

# Node Definitions
[[nodes]]
id        = 1
name      = "SATELIOT_1"
isDtnNode = true

[[nodes]]
id        = 2
name      = "SATELIOT_2"
isDtnNode = true

[[nodes]]
id        = 3
name      = "SATELIOT_3"
isDtnNode = true

[[nodes]]
id        = 4
name      = "SATELIOT_4"
isDtnNode = true

[[nodes]]
id        = 5
name      = "GS_Antarctica"
isDtnNode = true

[[nodes]]
id        = 6
name      = "GS_SVALBARD"
isDtnNode = true

[[nodes]]
id        = 7
name      = "GS_Antarctica_"
isDtnNode = false

# Edge Definitions
[[edges]]
from         = 5
to           = 7
start_in_sec = 0
end_in_sec   = 90000
bidirected   = true
range        = 0.00001

[[edges]]
from         = 2
to           = 6
start_in_sec = 740
end_in_sec   = 840
bidirected   = true
range        = 0.002128

[[edges]]
from         = 4
to           = 6
start_in_sec = 1910
end_in_sec   = 2020
bidirected   = true
range        = 0.002110

[[edges]]
from         = 2
to           = 5
start_in_sec = 3290
end_in_sec   = 3380
bidirected   = true
range        = 0.002246

[[edges]]
from         = 3
to           = 6
start_in_sec = 3780
end_in_sec   = 3890
bidirected   = true
range        = 0.002090

[[edges]]
from         = 4
to           = 5
start_in_sec = 4460
end_in_sec   = 4570
bidirected   = true
range        = 0.002178

[[edges]]
from         = 1
to           = 6
start_in_sec = 4830
end_in_sec   = 4930
bidirected   = true
range        = 0.002097

[[edges]]
from         = 3
to           = 5
start_in_sec = 6330
end_in_sec   = 6440
bidirected   = true
range        = 0.002159

[[edges]]
from         = 2
to           = 6
start_in_sec = 6460
end_in_sec   = 6550
bidirected   = true
range        = 0.002184

[[edges]]
from         = 1
to           = 5
start_in_sec = 7380
end_in_sec   = 7480
bidirected   = true
range        = 0.002230

[[edges]]
from         = 4
to           = 6
start_in_sec = 7640
end_in_sec   = 7720
bidirected   = true
range        = 0.002225

[[edges]]
from         = 3
to           = 6
start_in_sec = 9510
end_in_sec   = 9570
bidirected   = true
range        = 0.002231

[[edges]]
from         = 1
to           = 6
start_in_sec = 10560
end_in_sec   = 10610
bidirected   = true
range        = 0.002264

[[edges]]
from         = 2
to           = 6
start_in_sec = 12200
end_in_sec   = 12240
bidirected   = true
range        = 0.002327

[[edges]]
from         = 4
to           = 6
start_in_sec = 13370
end_in_sec   = 13410
bidirected   = true
range        = 0.002332

[[edges]]
from         = 3
to           = 6
start_in_sec = 15220
end_in_sec   = 15260
bidirected   = true
range        = 0.002298

[[edges]]
from         = 1
to           = 6
start_in_sec = 16260
end_in_sec   = 16310
bidirected   = true
range        = 0.002278

[[edges]]
from         = 2
to           = 6
start_in_sec = 17890
end_in_sec   = 17960
bidirected   = true
range        = 0.002264

[[edges]]
from         = 4
to           = 6
start_in_sec = 19060
end_in_sec   = 19130
bidirected   = true
range        = 0.002202

[[edges]]
from         = 3
to           = 6
start_in_sec = 20900
end_in_sec   = 20990
bidirected   = true
range        = 0.002150

[[edges]]
from         = 1
to           = 6
start_in_sec = 21940
end_in_sec   = 22040
bidirected   = true
range        = 0.002115

[[edges]]
from         = 2
to           = 6
start_in_sec = 23580
end_in_sec   = 23690
bidirected   = true
range        = 0.002115

[[edges]]
from         = 4
to           = 6
start_in_sec = 24760
end_in_sec   = 24860
bidirected   = true
range        = 0.002088

[[edges]]
from         = 3
to           = 6
start_in_sec = 26610
end_in_sec   = 26710
bidirected   = true
range        = 0.002106

[[edges]]
from         = 1
to           = 6
start_in_sec = 27660
end_in_sec   = 27750
bidirected   = true
range        = 0.002167

[[edges]]
from         = 2
to           = 6
start_in_sec = 29360
end_in_sec   = 29380
bidirected   = true
range        = 0.002341

[[edges]]
from         = 1
to           = 5
start_in_sec = 59800
end_in_sec   = 59850
bidirected   = true
range        = 0.002358

[[edges]]
from         = 2
to           = 5
start_in_sec = 61480
end_in_sec   = 61580
bidirected   = true
range        = 0.002173

[[edges]]
from         = 4
to           = 5
start_in_sec = 62640
end_in_sec   = 62750
bidirected   = true
range        = 0.002158

[[edges]]
from         = 3
to           = 5
start_in_sec = 64460
end_in_sec   = 64550
bidirected   = true
range        = 0.002173

[[edges]]
from         = 1
to           = 5
start_in_sec = 65510
end_in_sec   = 65580
bidirected   = true
range        = 0.002279

[[edges]]
from         = 3
to           = 6
start_in_sec = 84630
end_in_sec   = 84670
bidirected   = true
range        = 0.002283

[[edges]]
from         = 1
to           = 6
start_in_sec = 85660
end_in_sec   = 85730
bidirected   = true
range        = 0.002165

[[edges]]
from         = 2
to           = 6
start_in_sec = 87380
end_in_sec   = 87480
bidirected   = true
range        = 0.002116

[[edges]]
from         = 1
to           = 5
start_in_sec = 88250
end_in_sec   = 88260
bidirected   = true
range        = 0.002403

[[edges]]
from         = 4
to           = 6
start_in_sec = 88540
end_in_sec   = 88650
bidirected   = true
range        = 0.002109

[[edges]]
from         = 2
to           = 5
start_in_sec = 89940
end_in_sec   = 90030
bidirected   = true
range        = 0.002217

[[edges]]
from         = 3
to           = 6
start_in_sec = 90330
end_in_sec   = 90430
bidirected   = true
range        = 0.002069

[[edges]]
from         = 4
to           = 5
start_in_sec = 91090
end_in_sec   = 91200
bidirected   = true
range        = 0.002168

[[edges]]
from         = 1
to           = 6
start_in_sec = 91370
end_in_sec   = 91460
bidirected   = true
range        = 0.002080

[[edges]]
from         = 3
to           = 5
start_in_sec = 92870
end_in_sec   = 92980
bidirected   = true
range        = 0.002163

[[edges]]
from         = 2
to           = 6
start_in_sec = 93110
end_in_sec   = 93200
bidirected   = true
range        = 0.002195

[[edges]]
from         = 1
to           = 5
start_in_sec = 93920
end_in_sec   = 94010
bidirected   = true
range        = 0.002226

[[edges]]
from         = 4
to           = 6
start_in_sec = 94280
end_in_sec   = 94350
bidirected   = true
range        = 0.002219

[[edges]]
from         = 3
to           = 6
start_in_sec = 96060
end_in_sec   = 96120
bidirected   = true
range        = 0.002237

[[edges]]
from         = 1
to           = 6
start_in_sec = 97100
end_in_sec   = 97140
bidirected   = true
range        = 0.002258

[[edges]]
from         = 2
to           = 6
start_in_sec = 98840
end_in_sec   = 98880
bidirected   = true
range        = 0.002328

[[edges]]
from         = 4
to           = 6
start_in_sec = 100000
end_in_sec   = 100040
bidirected   = true
range        = 0.002331

[[edges]]
from         = 3
to           = 6
start_in_sec = 101770
end_in_sec   = 101800
bidirected   = true
range        = 0.002288

[[edges]]
from         = 1
to           = 6
start_in_sec = 102790
end_in_sec   = 102840
bidirected   = true
range        = 0.002275

[[edges]]
from         = 2
to           = 6
start_in_sec = 104530
end_in_sec   = 104600
bidirected   = true
range        = 0.002252

[[edges]]
from         = 4
to           = 6
start_in_sec = 105690
end_in_sec   = 105770
bidirected   = true
range        = 0.002209

[[edges]]
from         = 3
to           = 6
start_in_sec = 107440
end_in_sec   = 107530
bidirected   = true
range        = 0.002144

[[edges]]
from         = 1
to           = 6
start_in_sec = 108470
end_in_sec   = 108570
bidirected   = true
range        = 0.002109

[[edges]]
from         = 2
to           = 6
start_in_sec = 110230
end_in_sec   = 110330
bidirected   = true
range        = 0.002089

[[edges]]
from         = 4
to           = 6
start_in_sec = 111390
end_in_sec   = 111500
bidirected   = true
range        = 0.002115

[[edges]]
from         = 3
to           = 6
start_in_sec = 113160
end_in_sec   = 113250
bidirected   = true
range        = 0.002092

[[edges]]
from         = 1
to           = 6
start_in_sec = 114200
end_in_sec   = 114280
bidirected   = true
range        = 0.002160
