[contact_plan]
name                 = "contact_plan_sateliot"
max_time_in_sec      = 89360

[contact_plan.defaults]
rate_in_bits_per_sec = 300000000
range                = 1

# Node Definitions
[[nodes]]
id        = 1
name      = "SATELIOT_1"
isDtnNode = true

[[nodes]]
id        = 2
name      = "SATELIOT_2"
isDtnNode = true

[[nodes]]
id        = 3
name      = "SATELIOT_3"
isDtnNode = true

[[nodes]]
id        = 4
name      = "SATELIOT_4"
isDtnNode = true

[[nodes]]
id        = 5
name      = "GS_Antarctica"
isDtnNode = true

[[nodes]]
id        = 6
name      = "GS_SVALBARD"
isDtnNode = true

# Edge Definitions
[[edges]]
from         = 1
to           = 6
start_in_sec = 10
end_in_sec   = 280
bidirected   = true
range        = 0.002065

[[edges]]
from         = 2
to           = 6
start_in_sec = 810
end_in_sec   = 910
bidirected   = true
range        = 0.002116

[[edges]]
from         = 3
to           = 5
start_in_sec = 1580
end_in_sec   = 1690
bidirected   = true
range        = 0.002169

[[edges]]
from         = 4
to           = 6
start_in_sec = 2110
end_in_sec   = 2200
bidirected   = true
range        = 0.002144

[[edges]]
from         = 1
to           = 5
start_in_sec = 2720
end_in_sec   = 2830
bidirected   = true
range        = 0.002158

[[edges]]
from         = 2
to           = 5
start_in_sec = 3360
end_in_sec   = 3460
bidirected   = true
range        = 0.002196

[[edges]]
from         = 4
to           = 5
start_in_sec = 4680
end_in_sec   = 4740
bidirected   = true
range        = 0.002334

[[edges]]
from         = 3
to           = 6
start_in_sec = 4760
end_in_sec   = 4840
bidirected   = true
range        = 0.002203

[[edges]]
from         = 1
to           = 6
start_in_sec = 5900
end_in_sec   = 5970
bidirected   = true
range        = 0.002244

[[edges]]
from         = 2
to           = 6
start_in_sec = 6540
end_in_sec   = 6600
bidirected   = true
range        = 0.002292

[[edges]]
from         = 4
to           = 6
start_in_sec = 7840
end_in_sec   = 7890
bidirected   = true
range        = 0.002318

[[edges]]
from         = 3
to           = 6
start_in_sec = 10480
end_in_sec   = 10510
bidirected   = true
range        = 0.002305

[[edges]]
from         = 1
to           = 6
start_in_sec = 11620
end_in_sec   = 11650
bidirected   = true
range        = 0.002290

[[edges]]
from         = 2
to           = 6
start_in_sec = 12250
end_in_sec   = 12300
bidirected   = true
range        = 0.002317

[[edges]]
from         = 4
to           = 6
start_in_sec = 13540
end_in_sec   = 13600
bidirected   = true
range        = 0.002280

[[edges]]
from         = 3
to           = 6
start_in_sec = 16160
end_in_sec   = 16240
bidirected   = true
range        = 0.002197

[[edges]]
from         = 1
to           = 6
start_in_sec = 17290
end_in_sec   = 17380
bidirected   = true
range        = 0.002148

[[edges]]
from         = 2
to           = 6
start_in_sec = 17940
end_in_sec   = 18040
bidirected   = true
range        = 0.002160

[[edges]]
from         = 4
to           = 6
start_in_sec = 19230
end_in_sec   = 19330
bidirected   = true
range        = 0.002106

[[edges]]
from         = 3
to           = 6
start_in_sec = 21860
end_in_sec   = 21960
bidirected   = true
range        = 0.002067

[[edges]]
from         = 1
to           = 6
start_in_sec = 23000
end_in_sec   = 23100
bidirected   = true
range        = 0.002105

[[edges]]
from         = 2
to           = 6
start_in_sec = 23670
end_in_sec   = 23760
bidirected   = true
range        = 0.002173

[[edges]]
from         = 4
to           = 6
start_in_sec = 24980
end_in_sec   = 25040
bidirected   = true
range        = 0.002258

[[edges]]
from         = 1
to           = 2
start_in_sec = 0
end_in_sec   = 28910
bidirected   = true
range        = 0.016239

[[edges]]
from         = 2
to           = 5
start_in_sec = 55870
end_in_sec   = 55880
bidirected   = true
range        = 0.002406

[[edges]]
from         = 4
to           = 5
start_in_sec = 57120
end_in_sec   = 57210
bidirected   = true
range        = 0.002236

[[edges]]
from         = 3
to           = 5
start_in_sec = 59710
end_in_sec   = 59810
bidirected   = true
range        = 0.002128

[[edges]]
from         = 1
to           = 5
start_in_sec = 60840
end_in_sec   = 60940
bidirected   = true
range        = 0.002197

[[edges]]
from         = 2
to           = 5
start_in_sec = 61560
end_in_sec   = 61640
bidirected   = true
range        = 0.002263

[[edges]]
from         = 4
to           = 5
start_in_sec = 62880
end_in_sec   = 62890
bidirected   = true
range        = 0.002406

[[edges]]
from         = 1
to           = 6
start_in_sec = 81020
end_in_sec   = 81060
bidirected   = true
range        = 0.002276

[[edges]]
from         = 2
to           = 6
start_in_sec = 81740
end_in_sec   = 81820
bidirected   = true
range        = 0.002239

[[edges]]
from         = 4
to           = 6
start_in_sec = 83020
end_in_sec   = 83120
bidirected   = true
range        = 0.002155

[[edges]]
from         = 4
to           = 5
start_in_sec = 85590
end_in_sec   = 85660
bidirected   = true
range        = 0.002285

[[edges]]
from         = 3
to           = 6
start_in_sec = 85580
end_in_sec   = 85690
bidirected   = true
range        = 0.002086

[[edges]]
from         = 1
to           = 6
start_in_sec = 86710
end_in_sec   = 86820
bidirected   = true
range        = 0.002090

[[edges]]
from         = 2
to           = 6
start_in_sec = 87460
end_in_sec   = 87560
bidirected   = true
range        = 0.002124

[[edges]]
from         = 3
to           = 5
start_in_sec = 88130
end_in_sec   = 88230
bidirected   = true
range        = 0.002139

[[edges]]
from         = 4
to           = 6
start_in_sec = 88740
end_in_sec   = 88840
bidirected   = true
range        = 0.002175

[[edges]]
from         = 1
to           = 5
start_in_sec = 89260
end_in_sec   = 89360
bidirected   = true
range        = 0.002140

