[contact_plan]
name                 = "contact_plan_sateliot"
max_time_in_sec      = 61780

[contact_plan.defaults]
rate_in_bits_per_sec = 300000000
range                = 1

# Node Definitions
[[nodes]]
id        = 1
name      = "SATELIOT_1"
isDtnNode = true

[[nodes]]
id        = 2
name      = "SATELIOT_2"
isDtnNode = true

[[nodes]]
id        = 3
name      = "SATELIOT_3"
isDtnNode = true

[[nodes]]
id        = 4
name      = "SATELIOT_4"
isDtnNode = true

[[nodes]]
id        = 5
name      = "GS_Antarctica"
isDtnNode = true

[[nodes]]
id        = 6
name      = "GS_SVALBARD"
isDtnNode = true

# Edge Definitions
[[edges]]
from         = 1
to           = 5
start_in_sec = 5670
end_in_sec   = 5710
bidirected   = true
range        = 0.002378

[[edges]]
from         = 2
to           = 5
start_in_sec = 7230
end_in_sec   = 7330
bidirected   = true
range        = 0.002194

[[edges]]
from         = 4
to           = 5
start_in_sec = 8410
end_in_sec   = 8520
bidirected   = true
range        = 0.002155

[[edges]]
from         = 3
to           = 5
start_in_sec = 10310
end_in_sec   = 10410
bidirected   = true
range        = 0.002182

[[edges]]
from         = 1
to           = 5
start_in_sec = 11370
end_in_sec   = 11450
bidirected   = true
range        = 0.002277

[[edges]]
from         = 3
to           = 6
start_in_sec = 30490
end_in_sec   = 30520
bidirected   = true
range        = 0.002296

[[edges]]
from         = 1
to           = 6
start_in_sec = 31520
end_in_sec   = 31600
bidirected   = true
range        = 0.002196

[[edges]]
from         = 2
to           = 6
start_in_sec = 33140
end_in_sec   = 33240
bidirected   = true
range        = 0.002128

[[edges]]
from         = 4
to           = 6
start_in_sec = 34310
end_in_sec   = 34420
bidirected   = true
range        = 0.002110

[[edges]]
from         = 2
to           = 5
start_in_sec = 35690
end_in_sec   = 35780
bidirected   = true
range        = 0.002246

[[edges]]
from         = 3
to           = 6
start_in_sec = 36180
end_in_sec   = 36290
bidirected   = true
range        = 0.002090

[[edges]]
from         = 4
to           = 5
start_in_sec = 36860
end_in_sec   = 36970
bidirected   = true
range        = 0.002178

[[edges]]
from         = 1
to           = 6
start_in_sec = 37230
end_in_sec   = 37330
bidirected   = true
range        = 0.002097

[[edges]]
from         = 3
to           = 5
start_in_sec = 38730
end_in_sec   = 38840
bidirected   = true
range        = 0.002159

[[edges]]
from         = 2
to           = 6
start_in_sec = 38860
end_in_sec   = 38950
bidirected   = true
range        = 0.002184

[[edges]]
from         = 1
to           = 5
start_in_sec = 39780
end_in_sec   = 39880
bidirected   = true
range        = 0.002230

[[edges]]
from         = 4
to           = 6
start_in_sec = 40040
end_in_sec   = 40120
bidirected   = true
range        = 0.002225

[[edges]]
from         = 3
to           = 6
start_in_sec = 41910
end_in_sec   = 41970
bidirected   = true
range        = 0.002231

[[edges]]
from         = 1
to           = 6
start_in_sec = 42960
end_in_sec   = 43010
bidirected   = true
range        = 0.002264

[[edges]]
from         = 2
to           = 6
start_in_sec = 44600
end_in_sec   = 44640
bidirected   = true
range        = 0.002327

[[edges]]
from         = 4
to           = 6
start_in_sec = 45770
end_in_sec   = 45810
bidirected   = true
range        = 0.002332

[[edges]]
from         = 3
to           = 6
start_in_sec = 47620
end_in_sec   = 47660
bidirected   = true
range        = 0.002298

[[edges]]
from         = 1
to           = 6
start_in_sec = 48660
end_in_sec   = 48710
bidirected   = true
range        = 0.002278

[[edges]]
from         = 2
to           = 6
start_in_sec = 50290
end_in_sec   = 50360
bidirected   = true
range        = 0.002264

[[edges]]
from         = 4
to           = 6
start_in_sec = 51460
end_in_sec   = 51530
bidirected   = true
range        = 0.002202

[[edges]]
from         = 3
to           = 6
start_in_sec = 53300
end_in_sec   = 53390
bidirected   = true
range        = 0.002150

[[edges]]
from         = 1
to           = 6
start_in_sec = 54340
end_in_sec   = 54440
bidirected   = true
range        = 0.002115

[[edges]]
from         = 2
to           = 6
start_in_sec = 55980
end_in_sec   = 56090
bidirected   = true
range        = 0.002115

[[edges]]
from         = 4
to           = 6
start_in_sec = 57160
end_in_sec   = 57260
bidirected   = true
range        = 0.002088

[[edges]]
from         = 3
to           = 6
start_in_sec = 59010
end_in_sec   = 59110
bidirected   = true
range        = 0.002106

[[edges]]
from         = 1
to           = 6
start_in_sec = 60060
end_in_sec   = 60150
bidirected   = true
range        = 0.002167

[[edges]]
from         = 2
to           = 6
start_in_sec = 61760
end_in_sec   = 61780
bidirected   = true
range        = 0.002341

